steps:
  - name: gcr.io/cloud-builders/gsutil
    args: ["-m", "rsync", "-r", "-c", "-d", "./www.acpovexrobotics.com", "gs://meapp.in"]
  - name: gcr.io/cloud-builders/gsutil
    args: ["-m", "rsync", "-r", "-c", "-d", "./www.acpovexrobotics.com", "gs://acpovexrobotics.com"]